name: renovate

on:
  schedule:
    - cron: "@daily"
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"
      - "requirements.txt"
      - "setup.py"
      - "poetry.lock"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:42.66.11
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Fetch remote configuration
        run: curl -sL https://git.quad4.io/Quad4-Extra/renovate-config/raw/branch/master/config.js -o config.js
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: "config.js"
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
