FROM python:3.14-alpine AS builder

RUN apk update
RUN apk add --no-cache build-base libffi-dev cargo pkgconfig gcc python3-dev musl-dev linux-headers

WORKDIR /src

RUN pip install poetry

COPY pyproject.toml ./
COPY README.md ./
COPY rns_page_node ./rns_page_node

RUN poetry build --format wheel

FROM scratch AS dist

COPY --from=builder /src/dist .
