FROM python:3.14-slim

RUN apt-get update && apt-get install -y build-essential libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app
RUN pip install --no-cache-dir .

WORKDIR /app/tests

RUN chmod +x run_tests.sh

CMD ["bash", "run_tests.sh"] 